### PR TITLE
feat(select): add simple where utility functions

### PR DESCRIPTION
**Pull request by lundibundi**
* whereEq
* whereMore
* whereMoreEq
* whereLess
* whereLessEq

### CODE REVIEW

**Review by tshemsedinov — COMMENTED** [review]
This methods is ok, but later we need refactor all methods to declarative where syntax. It's better for storing and passing multiple where conditions in json format or as javascript object, less code, less methods, more declarative structures.

**Comment by belochub** [comment]
In my opinion, these methods are useless since each of them can be replaced with `builder.where()` with a relevant comparison operator as a second argument. These methods introduce Polish (prefix) notation for these comparison operators which is, in my opinion, less readable, due to it being significantly different from the resulting SQL, thus I would always prefer using `builder.where()` instead of these methods.

**Comment by lundibundi** [comment]
> In my opinion, these methods are useless since each of them can be replaced with builder.where()

Well, the same goes for every method in this package as it can be replaced with direct SQL anyway. This PR just provides more convenience methods to build a query just like the ones we have.

> These methods introduce Polish (prefix) notation for these comparison operators which is, in my opinion, less readable, due to it being significantly different from the resulting SQL,

Sure but other people may not think so and I see no harm in having a few more one-line methods that just delegate all of their functionality anyway and therefore won't introduce almost any maintenance burden.
It is not "significantly" different either from SQL or from the general `.where` method (`.where('key', '>', 100)` vs `.whereMore('key', 100)` vs `"key" > 100`). Moreover methods such as `.whereNotNull` are more different than this.

**Comment by tshemsedinov** [comment]
Please consider multiple alternative syntaxes here: https://github.com/metarhia/sql/issues/14
@lundibundi @belochub

**Pull request merged**
